"""The four pressure-simulation stimuli, ported exactly (Phase 2, Wave K, K2).

Each class here is a transcription of one pressure-simulation stimulus generator,
not a reimplementation -- see the docstring of each class for its source function.
The formulas are copied, not "improved": :mod:`tests.integration.test_stimulus_parity`
checks bit-for-bit agreement against a fixture generated by importing
pressure-simulation directly (``scripts/regenerate_stimulus_golden.py``).

All four return ``[T, H, W]`` from ``forward(xx, yy)`` (Fact K-c) and take a
constructor-level ``dt_ms`` (default ``1.0``, matching the source scripts'
hard-coded ``DT = 1.0``); every duration parameter (``total_ms``, ``ramp_ms``,
``ramp_up_ms``, ...) is in milliseconds and is converted to a sample count via
``round(duration_ms / dt_ms)``, which is the identity at the default ``dt_ms``.

Coordinates ``xx``, ``yy`` are ``[H, W]`` meshgrids in mm, ``indexing="ij"``
(Fact K-a): the first frame axis is x, the second is y.
"""

from __future__ import annotations

import math
from typing import Any, Dict, List, Optional, Tuple

import torch

from sensoryforge.stimuli.base import BaseStimulus, ParamSpec


def _n_samples(duration_ms: float, dt_ms: float) -> int:
    """Sample count for a duration in ms, at the default dt_ms=1.0 this is
    exactly the millisecond count (the source scripts' ``total_ms``/
    ``ramp_ms`` are used directly as sample counts)."""
    return max(int(round(float(duration_ms) / float(dt_ms))), 0)


def _symmetric_ramp(n: int, ramp_n: int) -> torch.Tensor:
    """Linear ramp in, hold at 1, linear ramp out -- ``gen_braille_H`` /
    ``gen_drifting_grating``'s envelope."""
    amp = torch.ones(n, dtype=torch.float32)
    if ramp_n > 0:
        rn = min(ramp_n, n // 2)
        if rn > 0:
            amp[:rn] = torch.linspace(0.0, 1.0, rn)
            amp[n - rn :] = torch.linspace(1.0, 0.0, rn)
    return amp


class RampGaussianStimulus(BaseStimulus):
    """Gaussian blob ramping to full amplitude then holding.

    Port of ``experiments/ncn2026/_harness.py::gen_ramp_gaussian`` in
    pressure-simulation (a reconstruction of the lost ``ramp_up.json``
    bundle stimulus).

    Attributes:
        total_ms: Total stimulus duration in ms.
        ramp_ms: Linear ramp-in duration in ms.
        sigma_mm: Gaussian spread in mm.
        dt_ms: Time step in ms (sample spacing).
    """

    def __init__(
        self,
        total_ms: float = 1100.0,
        ramp_ms: float = 50.0,
        sigma_mm: float = 1.0,
        *,
        dt_ms: float = 1.0,
    ) -> None:
        super().__init__()
        if sigma_mm <= 0:
            raise ValueError(f"sigma_mm must be positive, got {sigma_mm}")
        if dt_ms <= 0:
            raise ValueError(f"dt_ms must be positive, got {dt_ms}")
        self.total_ms = float(total_ms)
        self.ramp_ms = float(ramp_ms)
        self.sigma_mm = float(sigma_mm)
        self.dt_ms = float(dt_ms)

    def forward(self, xx: torch.Tensor, yy: torch.Tensor) -> torch.Tensor:
        """Render the ramping Gaussian blob.

        Args:
            xx: X-coordinate meshgrid ``[H, W]`` in mm.
            yy: Y-coordinate meshgrid ``[H, W]`` in mm.

        Returns:
            Frames ``[T, H, W]``, ``T = round(total_ms / dt_ms)``.
        """
        t_n = _n_samples(self.total_ms, self.dt_ms)
        # Clamped to the frame count: a caller-shortened total_ms (e.g. via
        # render_for_config's --duration clock, sensoryforge/stimuli/render.py
        # _clock_to_render_step) can leave the default ramp_ms longer than
        # the whole stimulus; _symmetric_ramp (this module) already clamps
        # the same way for the other three ported stimuli.
        ramp_n = min(_n_samples(self.ramp_ms, self.dt_ms), t_n)
        blob = torch.exp(-((xx**2 + yy**2) / (2.0 * self.sigma_mm**2))).to(
            dtype=torch.float32
        )
        amp = torch.ones(t_n, dtype=torch.float32, device=xx.device)
        if ramp_n > 0:
            amp[:ramp_n] = torch.linspace(0.0, 1.0, ramp_n, device=xx.device)
        return blob.unsqueeze(0) * amp.view(t_n, 1, 1)

    def reset_state(self) -> None:
        """Stateless; nothing to reset."""

    def to_dict(self) -> Dict[str, Any]:
        """Serialise parameters (F-045 round-trip completeness)."""
        return {
            "total_ms": self.total_ms,
            "ramp_ms": self.ramp_ms,
            "sigma_mm": self.sigma_mm,
            "dt_ms": self.dt_ms,
        }

    @classmethod
    def from_config(cls, config: Dict[str, Any]) -> "RampGaussianStimulus":
        """Construct from a configuration dictionary."""
        return cls(**config)

    @classmethod
    def get_param_spec(cls) -> List[ParamSpec]:
        """Parameter specifications for UI auto-generation."""
        return [
            ParamSpec(
                "total_ms",
                dtype="float",
                default=1100.0,
                min_val=1.0,
                max_val=20000.0,
                unit="ms",
                help="Total stimulus duration.",
                group="Temporal",
            ),
            ParamSpec(
                "ramp_ms",
                dtype="float",
                default=50.0,
                min_val=0.0,
                max_val=20000.0,
                unit="ms",
                help="Linear ramp-in duration before holding at full amplitude.",
                group="Temporal",
            ),
            ParamSpec(
                "sigma_mm",
                dtype="float",
                default=1.0,
                min_val=0.01,
                max_val=50.0,
                unit="mm",
                help="Gaussian spatial spread.",
                group="Spatial",
            ),
            ParamSpec(
                "dt_ms",
                dtype="float",
                default=1.0,
                min_val=0.01,
                max_val=100.0,
                unit="ms",
                help="Sample spacing.",
                group="Temporal",
                advanced=True,
            ),
        ]


class MovingEdgeStimulus(BaseStimulus):
    """An oriented edge sweeping from ``start`` to ``end`` during the plateau.

    Port of pressure-simulation's ``encoding/encode_runner.py::
    generate_stimulus_from_json`` with ``type="edge"``, ``motion="moving"``.
    Envelope: ``ramp_up_ms`` linear rise, ``plateau_ms`` hold, ``ramp_down_ms``
    linear fall, zero after. The edge centre interpolates linearly between
    ``start`` and ``end`` over the plateau only (``alpha=0`` during ramp-up,
    ``alpha=1`` during ramp-down); frame is
    ``exp(-p**2 / (2 * spread**2))`` with
    ``p = (xx - cx) * sin(theta) + (yy - cy) * cos(theta)``.

    Attributes:
        start: ``(x, y)`` mm start centre of the edge.
        end: ``(x, y)`` mm end centre of the edge.
        spread: Edge width (Gaussian sigma across the edge normal) in mm.
        orientation_deg: Edge orientation in degrees.
        amplitude: Peak amplitude.
        ramp_up_ms: Envelope linear rise duration in ms.
        plateau_ms: Envelope hold duration in ms (also the sweep duration).
        ramp_down_ms: Envelope linear fall duration in ms.
        total_ms: Total stimulus duration in ms.
        dt_ms: Time step in ms.
    """

    def __init__(
        self,
        start: Tuple[float, float] = (-7.11, 0.0),
        end: Tuple[float, float] = (7.0, 0.0),
        spread: float = 1.0,
        orientation_deg: float = 50.0,
        amplitude: float = 1.0,
        ramp_up_ms: float = 20.0,
        plateau_ms: float = 300.0,
        ramp_down_ms: float = 10.0,
        total_ms: float = 330.0,
        *,
        dt_ms: float = 1.0,
    ) -> None:
        super().__init__()
        if spread <= 0:
            raise ValueError(f"spread must be positive, got {spread}")
        if dt_ms <= 0:
            raise ValueError(f"dt_ms must be positive, got {dt_ms}")
        self.start = (float(start[0]), float(start[1]))
        self.end = (float(end[0]), float(end[1]))
        self.spread = float(spread)
        self.orientation_deg = float(orientation_deg)
        self.amplitude = float(amplitude)
        self.ramp_up_ms = float(ramp_up_ms)
        self.plateau_ms = float(plateau_ms)
        self.ramp_down_ms = float(ramp_down_ms)
        self.total_ms = float(total_ms)
        self.dt_ms = float(dt_ms)

    def forward(self, xx: torch.Tensor, yy: torch.Tensor) -> torch.Tensor:
        """Render the moving edge.

        Args:
            xx: X-coordinate meshgrid ``[H, W]`` in mm.
            yy: Y-coordinate meshgrid ``[H, W]`` in mm.

        Returns:
            Frames ``[T, H, W]`` on the half-step-guarded time axis
            ``arange(0, total_ms + 0.5*dt_ms, dt_ms)``.
        """
        device = xx.device
        dtype = torch.float32
        time_ms = torch.arange(
            0.0, self.total_ms + 0.5 * self.dt_ms, self.dt_ms, device=device
        )
        t_n = time_ms.numel()

        ramp_up, plateau, ramp_down = (
            self.ramp_up_ms,
            self.plateau_ms,
            self.ramp_down_ms,
        )
        down_start = ramp_up + plateau
        total_dur = ramp_up + plateau + ramp_down

        amp = torch.zeros_like(time_ms)
        if ramp_up > 0:
            up_mask = time_ms < ramp_up
            amp[up_mask] = time_ms[up_mask] / ramp_up
        else:
            amp[time_ms < ramp_up + 1e-6] = 1.0
        amp[(time_ms >= ramp_up) & (time_ms < down_start)] = 1.0
        if ramp_down > 0:
            down_mask = (time_ms >= down_start) & (time_ms <= down_start + ramp_down)
            amp[down_mask] = torch.clamp(
                1.0 - (time_ms[down_mask] - down_start) / ramp_down, 0.0, 1.0
            )
        amp = torch.where(time_ms > total_dur, torch.zeros_like(amp), amp)
        amp = amp.clamp(0.0, 1.0) * self.amplitude

        sx, sy = self.start
        ex, ey = self.end
        dist = math.hypot(ex - sx, ey - sy)

        # theta as a 0-d tensor, sin/cos via torch (not python math.sin/cos)
        # to match pressure-simulation's edge_stimulus_torch bit-for-bit.
        theta = torch.tensor(
            math.radians(self.orientation_deg), device=device, dtype=dtype
        )
        sin_theta = torch.sin(theta)
        cos_theta = torch.cos(theta)
        xx_f = xx.to(dtype=dtype)
        yy_f = yy.to(dtype=dtype)

        # Per-frame centre interpolation and edge rendering, looped exactly
        # as pressure-simulation's generate_stimulus_from_json does (python
        # float arithmetic for cx/cy, one edge_stimulus_torch call per
        # frame): this is required for bit-exact parity -- a vectorised
        # tensor computation of cx/cy rounds differently in float32.
        frames = torch.zeros(t_n, *xx.shape, dtype=dtype, device=device)
        for idx in range(t_n):
            t = float(time_ms[idx])
            if plateau > 0 and dist > 1e-6:
                if t <= ramp_up:
                    alpha = 0.0
                elif t >= ramp_up + plateau:
                    alpha = 1.0
                else:
                    alpha = (t - ramp_up) / plateau
                cx = sx + alpha * (ex - sx)
                cy = sy + alpha * (ey - sy)
            else:
                cx, cy = sx, sy
            p = (xx_f - cx) * sin_theta + (yy_f - cy) * cos_theta
            frames[idx] = torch.exp(-(p**2) / (2.0 * self.spread**2)) * amp[idx]
        return frames

    def reset_state(self) -> None:
        """Stateless; nothing to reset."""

    def to_dict(self) -> Dict[str, Any]:
        """Serialise parameters (F-045 round-trip completeness)."""
        return {
            "start": list(self.start),
            "end": list(self.end),
            "spread": self.spread,
            "orientation_deg": self.orientation_deg,
            "amplitude": self.amplitude,
            "ramp_up_ms": self.ramp_up_ms,
            "plateau_ms": self.plateau_ms,
            "ramp_down_ms": self.ramp_down_ms,
            "total_ms": self.total_ms,
            "dt_ms": self.dt_ms,
        }

    @classmethod
    def from_config(cls, config: Dict[str, Any]) -> "MovingEdgeStimulus":
        """Construct from a configuration dictionary."""
        cfg = dict(config)
        if "start" in cfg:
            cfg["start"] = tuple(cfg["start"])
        if "end" in cfg:
            cfg["end"] = tuple(cfg["end"])
        return cls(**cfg)

    @classmethod
    def get_param_spec(cls) -> List[ParamSpec]:
        """Parameter specifications for UI auto-generation."""
        return [
            ParamSpec(
                "spread",
                dtype="float",
                default=1.0,
                min_val=0.01,
                max_val=50.0,
                unit="mm",
                help="Edge width (Gaussian sigma across the normal).",
                group="Spatial",
            ),
            ParamSpec(
                "orientation_deg",
                dtype="float",
                default=50.0,
                min_val=-360.0,
                max_val=360.0,
                unit="deg",
                help="Edge orientation.",
                group="Spatial",
            ),
            ParamSpec(
                "amplitude",
                dtype="float",
                default=1.0,
                min_val=0.0,
                max_val=1000.0,
                help="Peak amplitude.",
                group="Amplitude",
            ),
            ParamSpec(
                "ramp_up_ms",
                dtype="float",
                default=20.0,
                min_val=0.0,
                max_val=20000.0,
                unit="ms",
                group="Temporal",
            ),
            ParamSpec(
                "plateau_ms",
                dtype="float",
                default=300.0,
                min_val=0.0,
                max_val=20000.0,
                unit="ms",
                group="Temporal",
            ),
            ParamSpec(
                "ramp_down_ms",
                dtype="float",
                default=10.0,
                min_val=0.0,
                max_val=20000.0,
                unit="ms",
                group="Temporal",
            ),
            ParamSpec(
                "total_ms",
                dtype="float",
                default=330.0,
                min_val=1.0,
                max_val=20000.0,
                unit="ms",
                group="Temporal",
            ),
            ParamSpec(
                "dt_ms",
                dtype="float",
                default=1.0,
                min_val=0.01,
                max_val=100.0,
                unit="ms",
                group="Temporal",
                advanced=True,
            ),
        ]


class BrailleStimulus(BaseStimulus):
    """A braille cell sliding along the y axis.

    Port of ``scripts/ebkf/_ebkf_pres_movies.py::gen_braille_H`` in
    pressure-simulation. Dots are given as ``(row, col)`` offsets in mm
    relative to the moving cell centre; the default is the letter H (dots 1,
    2, 5 of the standard 6-dot cell). Motion is along the **second** axis
    (``yy``); dot rows (the ``xx`` axis) are fixed. The cell centre is
    ``cy = -7.0 + v_mms * t_s``.

    Attributes:
        dot_offsets: List of ``(row_offset_mm, col_offset_mm)`` dot positions
            relative to the cell centre.
        total_ms: Total stimulus duration in ms.
        ramp_ms: Ramp in/out duration in ms (each side, capped at ``T // 2``).
        v_mms: Sweep speed in mm/s.
        sigma_dot: Per-dot Gaussian spread in mm.
        dt_ms: Time step in ms.
    """

    _DEFAULT_DOT_OFFSETS = [(-1.5, -1.5), (1.5, -1.5), (1.5, 1.5)]  # letter H

    def __init__(
        self,
        dot_offsets: Optional[List[Tuple[float, float]]] = None,
        total_ms: float = 900.0,
        ramp_ms: float = 75.0,
        v_mms: float = 20.0,
        sigma_dot: float = 0.40,
        *,
        dt_ms: float = 1.0,
    ) -> None:
        super().__init__()
        if sigma_dot <= 0:
            raise ValueError(f"sigma_dot must be positive, got {sigma_dot}")
        if dt_ms <= 0:
            raise ValueError(f"dt_ms must be positive, got {dt_ms}")
        self.dot_offsets = (
            list(self._DEFAULT_DOT_OFFSETS)
            if dot_offsets is None
            else [(float(r), float(c)) for r, c in dot_offsets]
        )
        self.total_ms = float(total_ms)
        self.ramp_ms = float(ramp_ms)
        self.v_mms = float(v_mms)
        self.sigma_dot = float(sigma_dot)
        self.dt_ms = float(dt_ms)

    def forward(self, xx: torch.Tensor, yy: torch.Tensor) -> torch.Tensor:
        """Render the sliding braille cell.

        Args:
            xx: X-coordinate meshgrid ``[H, W]`` in mm.
            yy: Y-coordinate meshgrid ``[H, W]`` in mm.

        Returns:
            Frames ``[T, H, W]``, ``T = round(total_ms / dt_ms)``.
        """
        device = xx.device
        t_n = _n_samples(self.total_ms, self.dt_ms)
        ramp_n = _n_samples(self.ramp_ms, self.dt_ms)

        t_s = (
            torch.arange(t_n, dtype=torch.float32, device=device) * self.dt_ms / 1000.0
        )
        cy = (-7.0 + self.v_mms * t_s).view(t_n, 1, 1)

        xx3 = xx.unsqueeze(0).to(dtype=torch.float32)
        yy3 = yy.unsqueeze(0).to(dtype=torch.float32)

        stim = torch.zeros(t_n, *xx.shape, dtype=torch.float32, device=device)
        for dr, dc in self.dot_offsets:
            dot_row = 0.0 + dr
            dot_col = cy + dc
            stim = stim + torch.exp(
                -((xx3 - dot_row) ** 2 + (yy3 - dot_col) ** 2)
                / (2.0 * self.sigma_dot**2)
            )

        amp = _symmetric_ramp(t_n, ramp_n).to(device=device)
        return (stim * amp.view(t_n, 1, 1)).clamp(0.0, float(len(self.dot_offsets)))

    def reset_state(self) -> None:
        """Stateless; nothing to reset."""

    def to_dict(self) -> Dict[str, Any]:
        """Serialise parameters (F-045 round-trip completeness)."""
        return {
            "dot_offsets": [list(d) for d in self.dot_offsets],
            "total_ms": self.total_ms,
            "ramp_ms": self.ramp_ms,
            "v_mms": self.v_mms,
            "sigma_dot": self.sigma_dot,
            "dt_ms": self.dt_ms,
        }

    @classmethod
    def from_config(cls, config: Dict[str, Any]) -> "BrailleStimulus":
        """Construct from a configuration dictionary."""
        cfg = dict(config)
        if "dot_offsets" in cfg and cfg["dot_offsets"] is not None:
            cfg["dot_offsets"] = [tuple(d) for d in cfg["dot_offsets"]]
        return cls(**cfg)

    @classmethod
    def get_param_spec(cls) -> List[ParamSpec]:
        """Parameter specifications for UI auto-generation."""
        return [
            ParamSpec(
                "total_ms",
                dtype="float",
                default=900.0,
                min_val=1.0,
                max_val=20000.0,
                unit="ms",
                group="Temporal",
            ),
            ParamSpec(
                "ramp_ms",
                dtype="float",
                default=75.0,
                min_val=0.0,
                max_val=20000.0,
                unit="ms",
                group="Temporal",
            ),
            ParamSpec(
                "v_mms",
                dtype="float",
                default=20.0,
                min_val=-1000.0,
                max_val=1000.0,
                unit="mm/s",
                help="Sweep speed along the yy axis.",
                group="Spatial",
            ),
            ParamSpec(
                "sigma_dot",
                dtype="float",
                default=0.40,
                min_val=0.01,
                max_val=50.0,
                unit="mm",
                group="Spatial",
            ),
            ParamSpec(
                "dt_ms",
                dtype="float",
                default=1.0,
                min_val=0.01,
                max_val=100.0,
                unit="ms",
                group="Temporal",
                advanced=True,
            ),
        ]


class DriftingGratingStimulus(BaseStimulus):
    """A sinusoidal grating drifting along x, simulating a textured scan.

    Port of ``scripts/ebkf/_ebkf_pres_movies.py::gen_drifting_grating`` in
    pressure-simulation. ``phase = 2*pi*spatial_freq*(xx + v_mms*t_s)``,
    ``frame = 0.5*(1 + cos(phase))``, clamped to ``[0, 1]`` after the same
    symmetric ramp envelope as :class:`BrailleStimulus`.

    Attributes:
        total_ms: Total stimulus duration in ms.
        ramp_ms: Ramp in/out duration in ms (each side, capped at ``T // 2``).
        spatial_freq: Spatial frequency in cycles/mm.
        v_mms: Drift speed in mm/s.
        dt_ms: Time step in ms.
    """

    def __init__(
        self,
        total_ms: float = 1000.0,
        ramp_ms: float = 100.0,
        spatial_freq: float = 0.25,
        v_mms: float = 15.0,
        *,
        dt_ms: float = 1.0,
    ) -> None:
        super().__init__()
        if dt_ms <= 0:
            raise ValueError(f"dt_ms must be positive, got {dt_ms}")
        self.total_ms = float(total_ms)
        self.ramp_ms = float(ramp_ms)
        self.spatial_freq = float(spatial_freq)
        self.v_mms = float(v_mms)
        self.dt_ms = float(dt_ms)

    def forward(self, xx: torch.Tensor, yy: torch.Tensor) -> torch.Tensor:
        """Render the drifting grating.

        Args:
            xx: X-coordinate meshgrid ``[H, W]`` in mm.
            yy: Y-coordinate meshgrid ``[H, W]`` in mm (unused; the grating
                drifts along ``xx`` only, matching the source).

        Returns:
            Frames ``[T, H, W]``, ``T = round(total_ms / dt_ms)``.
        """
        device = xx.device
        t_n = _n_samples(self.total_ms, self.dt_ms)
        ramp_n = _n_samples(self.ramp_ms, self.dt_ms)

        t_s = (
            torch.arange(t_n, dtype=torch.float32, device=device).view(t_n, 1, 1)
            * self.dt_ms
            / 1000.0
        )
        phase = (
            2.0
            * math.pi
            * self.spatial_freq
            * (xx.unsqueeze(0).to(dtype=torch.float32) + self.v_mms * t_s)
        )
        grating = 0.5 * (1.0 + torch.cos(phase))

        amp = _symmetric_ramp(t_n, ramp_n).to(device=device)
        return (grating * amp.view(t_n, 1, 1)).clamp(0.0, 1.0)

    def reset_state(self) -> None:
        """Stateless; nothing to reset."""

    def to_dict(self) -> Dict[str, Any]:
        """Serialise parameters (F-045 round-trip completeness)."""
        return {
            "total_ms": self.total_ms,
            "ramp_ms": self.ramp_ms,
            "spatial_freq": self.spatial_freq,
            "v_mms": self.v_mms,
            "dt_ms": self.dt_ms,
        }

    @classmethod
    def from_config(cls, config: Dict[str, Any]) -> "DriftingGratingStimulus":
        """Construct from a configuration dictionary."""
        return cls(**config)

    @classmethod
    def get_param_spec(cls) -> List[ParamSpec]:
        """Parameter specifications for UI auto-generation."""
        return [
            ParamSpec(
                "total_ms",
                dtype="float",
                default=1000.0,
                min_val=1.0,
                max_val=20000.0,
                unit="ms",
                group="Temporal",
            ),
            ParamSpec(
                "ramp_ms",
                dtype="float",
                default=100.0,
                min_val=0.0,
                max_val=20000.0,
                unit="ms",
                group="Temporal",
            ),
            ParamSpec(
                "spatial_freq",
                dtype="float",
                default=0.25,
                min_val=0.001,
                max_val=100.0,
                unit="cyc/mm",
                group="Spatial",
            ),
            ParamSpec(
                "v_mms",
                dtype="float",
                default=15.0,
                min_val=-1000.0,
                max_val=1000.0,
                unit="mm/s",
                group="Spatial",
            ),
            ParamSpec(
                "dt_ms",
                dtype="float",
                default=1.0,
                min_val=0.01,
                max_val=100.0,
                unit="ms",
                group="Temporal",
                advanced=True,
            ),
        ]
